### ISSUE TITLE
how to decrypt pdf

### ISSUE THREAD

**Issue by wingjson** [ancwrd1/qpdf-rs#3]
hi，how to decrypt

**Comment by ancwrd1** [comment]
You can use `QPdf::read_encrypted` constructor which accepts a path and a password.
Then you can write it into unencrypted PDF.

Example is provided here: https://github.com/ancwrd1/qpdf-rs/blob/dac0510910bf68455f0f2e19936bb1a9b64f71c9/qpdf-rs/tests/test_qpdf.rs#L272
