### ISSUE TITLE
Encrypt with password

### ISSUE THREAD

**Issue by dvishal485** [ancwrd1/qpdf-rs#4]
Can we not use `qpdf-rs` to encrypt pdf file?
I couldn't find any similiar method to encrypt a non-encrypted pdf file in the documentation.
Here is the [relevant documentation from qpdf](https://qpdf.readthedocs.io/en/stable/cli.html#option-encrypt)

**Comment by ancwrd1** [comment]
Hi, it's not in the current implementation, I haven't figured out yet the ergonomic way of adding it in the Rust code. It's quite complicated with tons of parameters: https://qpdf.readthedocs.io/en/stable/encryption.html#pdf-encryption

But in principle it's possible to implement.

**Comment by dvishal485** [comment]
Okay! Thanks for the quick response and more importantly for this project. Great work.

**Comment by ancwrd1** [comment]
I have added some initial support for encryption.

**Comment by dvishal485** [comment]
Thanks a lot for the prompt response!
